CREATE TABLE jb_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE jb_listings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    location VARCHAR(255),
    contact VARCHAR(255),
    description TEXT,
    price DECIMAL(6,2),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);