CREATE DATABASE auth_demo;
    CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);